# Generated by Django 5.1.6 on 2025-02-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(default='cea55778-5', max_length=10, unique=True),
        ),
    ]
